medallon:
  target: dev
  outputs:
    dev:
      type: postgres
      host: bbdd_postgres
      user: admin
      password: admin123
      port: 5432
      dbname: ejercicio_db
      schema: staging
      threads: 4
